apiVersion: v1
baseDomain: #(TODO)
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - #(TODO)
      type: #(TODO)
  replicas: #(TODO)
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - #(TODO)
      type: #(TODO)
  replicas: 3
metadata:
  creationTimestamp: null
  name: #(TODO)
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.30.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: #(TODO)
    userTags:
      #(TODO)
publish: External
pullSecret: #'(TODO)'
sshKey: | #(TODO)
